AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CareerCanvas Auth Service - Serverless API

Parameters:
  DatabaseUrl:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  MailHost:
    Type: String
  MailPassword:
    Type: String
  MailPort:
    Type: String
  MailUsername:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs18.x

Resources:
  # API Gateway
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: "2.0"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: NONE
      DisableExecuteApiEndpoint: false
      TracingEnabled: false
      # Set local development port
      Variables:
        Port: 8001

  RequestEmailOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib
      Handler: index.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/otp/request/email
            Method: post
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          MAIL_HOST: !Ref MailHost
          MAIL_PASSWORD: !Ref MailPassword
          MAIL_PORT: !Ref MailPort
          MAIL_USERNAME: !Ref MailUsername

Outputs:
  AuthApiEndpoint:
    Description: "API Gateway endpoint URL for the Auth service"
    Value: !Sub "https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  RequestEmailOtpFunction:
    Description: "Request Email OTP Lambda Function ARN"
    Value: !GetAtt RequestEmailOtpFunction.Arn
